version = 1

[[analyzers]]
name = "cpp"
enabled = true
include_patterns = [
    "**/*.cpp",
    "**/*.h"
]
exclude_patterns = [
    "bin/",
    "saves/",
    "**/*.dat",
    "exec.sh",
    "reset_data.sh"
]
